// GENERATED by scripts/generate-pages.mjs from the old TanStack route files.
// Nesting mirrors TanStack's flat-file rules. Safe to hand-edit from here on.
import type React from "react";
import { Navigate, createBrowserRouter } from "react-router-dom";
import { AppRoot, RootErrorBoundary, RootLoading, RootNotFound } from "./App";
import { GuestOnly, RequireAuth } from "@/lib/auth/auth-guards";
import { ReputationInsightsRedirectPage, ReputationReviewsRedirectPage } from "@/pages/reputation/ReputationRedirectPage";

/** Pages load on first visit (each is its own chunk), so the first download stays small. */
const page = (module: { default: React.ComponentType }) => ({ Component: module.default });

export const router = createBrowserRouter([
  {
    path: "/",
    Component: AppRoot,
    ErrorBoundary: RootErrorBoundary,
    HydrateFallback: RootLoading,
    children: [
      { index: true, lazy: () => import("@/pages/home/HomePage").then(page) },
      {
        // Signed-in pages: no valid token sends the user to /login.
        Component: RequireAuth,
        children: [
          { path: "dashboard", lazy: () => import("@/pages/dashboard/DashboardPage").then(page) },
          {
            path: "locations",
            lazy: () => import("@/pages/locations/LocationsLayout").then(page),
            children: [
              { index: true, lazy: () => import("@/pages/locations/LocationsIndexPage").then(page) },
              { path: "add", lazy: () => import("@/pages/locations/LocationsAddPage").then(page) },
              { path: ":locationId", lazy: () => import("@/pages/locations/location-detail/LocationDetailIndexPage").then(page) },
              { path: ":locationId/setup", lazy: () => import("@/pages/locations/location-detail/LocationSetupPage").then(page) },
              { path: ":locationId/reports", lazy: () => import("@/pages/locations/location-detail/report/LocationReportsPage").then(page) },
              { path: ":locationId/reports/:reportId", lazy: () => import("@/pages/locations/location-detail/report/LocationReportDetailPage").then(page) },
              {
                path: ":locationId/gbp",
                lazy: () => import("@/pages/locations/location-detail/gbp/GbpLayout").then(page),
                children: [
                  { index: true, lazy: () => import("@/pages/locations/location-detail/gbp/GbpIndexPage").then(page) },
                  { path: "posts", lazy: () => import("@/pages/locations/location-detail/gbp/GbpPostsPage").then(page) },
                  { path: "reviews", lazy: () => import("@/pages/locations/location-detail/gbp/GbpReviewsPage").then(page) },
                  {
                    path: "audit",
                    lazy: () => import("@/pages/locations/location-detail/gbp/audit/GbpAuditLayout").then(page),
                    children: [
                      { index: true, lazy: () => import("@/pages/locations/location-detail/gbp/audit/GbpAuditIndexPage").then(page) },
                      { path: "competitors", lazy: () => import("@/pages/locations/location-detail/gbp/audit/GbpAuditCompetitorsPage").then(page) },
                    ],
                  },
                ],
              },
              {
                path: ":locationId/rankings",
                lazy: () => import("@/pages/locations/location-detail/rankings/RankingsLayout").then(page),
                children: [
                  { index: true, lazy: () => import("@/pages/locations/location-detail/rankings/RankingsIndexPage").then(page) },
                  { path: "tracker", lazy: () => import("@/pages/locations/location-detail/rankings/RankingsTrackerPage").then(page) },
                  { path: "keywords", lazy: () => import("@/pages/locations/location-detail/rankings/RankingsKeywordsPage").then(page) },
                  { path: "groups", lazy: () => import("@/pages/locations/location-detail/rankings/RankingsGroupsPage").then(page) },
                  { path: "grid", lazy: () => import("@/pages/locations/location-detail/rankings/RankingsGridPage").then(page) },
                  { path: "map", lazy: () => import("@/pages/locations/location-detail/rankings/RankingsMapPage").then(page) },
                  { path: "competitors", lazy: () => import("@/pages/locations/location-detail/rankings/RankingsCompetitorsPage").then(page) },
                ],
              },
              {
                path: ":locationId/reputation",
                lazy: () => import("@/pages/locations/location-detail/reputation/ReputationLayout").then(page),
                children: [
                  { index: true, lazy: () => import("@/pages/locations/location-detail/reputation/ReviewsPage").then(page) },
                  { path: "insights", lazy: () => import("@/pages/locations/location-detail/reputation/InsightsPage").then(page) },
                ],
              },
              { path: ":locationId/citations", lazy: () => import("@/pages/locations/location-detail/citations/CitationsIndexPage").then(page) },
              { path: ":locationId/citations/:citationId", lazy: () => import("@/pages/locations/location-detail/citations/CitationDetailPage").then(page) },
              { path: ":locationId/competitors", lazy: () => import("@/pages/locations/location-detail/competitors/CompetitorsIndexPage").then(page) },
              { path: ":locationId/competitors/:competitorId", lazy: () => import("@/pages/locations/location-detail/competitors/CompetitorDetailPage").then(page) },
            ],
          },
          { path: "rankings", lazy: () => import("@/pages/rankings/RankingsIndexPage").then(page) },

          { path: "rankings/tracker", lazy: () => import("@/pages/rankings/RankingsTrackerRedirectPage").then(page) },
          { path: "rankings/keywords", lazy: () => import("@/pages/rankings/RankingsKeywordsPage").then(page) },
          { path: "rankings/keyword-groups", lazy: () => import("@/pages/rankings/RankingsKeywordGroupsPage").then(page) },
          { path: "rankings/map-rankings", lazy: () => import("@/pages/rankings/RankingsMapRankingsPage").then(page) },
          { path: "rankings/local-search-grid", lazy: () => import("@/pages/rankings/RankingsLocalSearchGridPage").then(page) },
          { path: "gbp", lazy: () => import("@/pages/gbp/GbpIndexPage").then(page) },
          { path: "gbp/audit", lazy: () => import("@/pages/gbp/GbpAuditPage").then(page) },
          { path: "gbp/competitors", lazy: () => import("@/pages/gbp/GbpCompetitorsRedirectPage").then(page) },
          // Reviews moved to Reputation; the old addresses still work.
          { path: "gbp/reviews", element: <Navigate to="/reputation/reviews" replace /> },
          { path: "gbp/posts", lazy: () => import("@/pages/gbp/GbpPostsPage").then(page) },
          { path: "gbp/ai-posts", lazy: () => import("@/pages/gbp/GbpAiPostsPage").then(page) },
          { path: "gbp/ai-posts/create", lazy: () => import("@/pages/gbp/GbpAiPostCreatePage").then(page) },
          { path: "gbp/ai-posts/:postId", lazy: () => import("@/pages/gbp/GbpAiPostDetailPage").then(page) },
          { path: "gbp/review-management", element: <Navigate to="/reputation/review-management" replace /> },
          { path: "gbp/review-management/automation", element: <Navigate to="/reputation/review-management/automation" replace /> },
          { path: "reputation", Component: ReputationReviewsRedirectPage },
          { path: "reputation/reviews", Component: ReputationReviewsRedirectPage },
          { path: "reputation/insights", Component: ReputationInsightsRedirectPage },
          // Review Management was merged into Reviews; auto-reply isn't built yet.
          { path: "reputation/review-management", element: <Navigate to="/reputation/reviews" replace /> },
          { path: "reputation/review-management/automation", element: <Navigate to="/reputation/reviews" replace /> },
          // Google OAuth redirect target for the Business Profile connection.
          { path: "gbp/connect/callback", lazy: () => import("@/pages/gbp/GbpConnectCallbackPage").then(page) },
          { path: "citations", lazy: () => import("@/pages/citations/CitationsPage").then(page) },
          { path: "competitors", lazy: () => import("@/pages/competitors/CompetitorsPage").then(page) },
          { path: "ai-visibility", lazy: () => import("@/pages/ai-visibility/AiVisibilityPage").then(page) },
          { path: "reports", lazy: () => import("@/pages/reports/ReportsIndexPage").then(page) },
          { path: "reports/create", lazy: () => import("@/pages/reports/ReportsCreatePage").then(page) },
          { path: "reports/scheduled", lazy: () => import("@/pages/reports/ReportsScheduledPage").then(page) },
          { path: "reports/:reportId", lazy: () => import("@/pages/reports/ReportDetailPage").then(page) },
          { path: "clients", lazy: () => import("@/pages/clients/ClientsIndexPage").then(page) },
          {
            path: "clients/:clientId",
            lazy: () => import("@/pages/clients/client-detail/ClientLayout").then(page),
            children: [
              { index: true, lazy: () => import("@/pages/clients/client-detail/ClientIndexPage").then(page) },
              { path: "locations", lazy: () => import("@/pages/clients/client-detail/ClientLocationsPage").then(page) },
              { path: "users", lazy: () => import("@/pages/clients/client-detail/ClientUsersPage").then(page) },
            ],
          },
          { path: "automations", lazy: () => import("@/pages/automations/AutomationsIndexPage").then(page) },
          { path: "automations/create", lazy: () => import("@/pages/automations/AutomationsCreatePage").then(page) },
          { path: "automations/:automationId", lazy: () => import("@/pages/automations/AutomationDetailPage").then(page) },
          {
            path: "settings",
            lazy: () => import("@/pages/settings/SettingsLayout").then(page),
            children: [
              { index: true, lazy: () => import("@/pages/settings/SettingsIndexPage").then(page) },
              { path: "profile", lazy: () => import("@/pages/settings/SettingsProfilePage").then(page) },
              { path: "billing", lazy: () => import("@/pages/settings/SettingsBillingPage").then(page) },
              { path: "team", lazy: () => import("@/pages/settings/SettingsTeamPage").then(page) },
              { path: "integrations", lazy: () => import("@/pages/settings/SettingsIntegrationsPage").then(page) },
              { path: "notifications", lazy: () => import("@/pages/settings/SettingsNotificationsPage").then(page) },
              { path: "white-label", lazy: () => import("@/pages/white-label/SettingsWhiteLabelPage").then(page) },
              { path: "white-label/preview/:reportId?", lazy: () => import("@/pages/white-label/WhiteLabelPreviewPage").then(page) },
            ],
          },
          { path: "notifications", lazy: () => import("@/pages/notifications/NotificationsPage").then(page) },
          { path: "help", lazy: () => import("@/pages/help/HelpPage").then(page) },
          { path: "onboarding", lazy: () => import("@/pages/onboarding/OnboardingIndexPage").then(page) },
          { path: "onboarding/business", lazy: () => import("@/pages/onboarding/OnboardingBusinessPage").then(page) },
          { path: "onboarding/agency", lazy: () => import("@/pages/onboarding/OnboardingAgencyPage").then(page) },
        ],
      },
      {
        // Sign In / Sign Up: an already signed-in user goes straight to the app.
        Component: GuestOnly,
        children: [
          { path: "login", lazy: () => import("@/pages/auth/LoginPage").then(page) },
          { path: "signup", lazy: () => import("@/pages/auth/SignupPage").then(page) },
        ],
      },
      { path: "forgot-password", lazy: () => import("@/pages/auth/ForgotPasswordPage").then(page) },
      { path: "reset-password", lazy: () => import("@/pages/auth/ResetPasswordPage").then(page) },
      { path: "verify-email", lazy: () => import("@/pages/auth/VerifyEmailPage").then(page) },
      { path: "invite", lazy: () => import("@/pages/auth/InvitePage").then(page) },
      { path: "403", lazy: () => import("@/pages/errors/ForbiddenPage").then(page) },
      { path: "404", lazy: () => import("@/pages/errors/NotFoundPage").then(page) },
      { path: "*", Component: RootNotFound },
    ],
  },
]);

export default router;
