// GENERATED by scripts/generate-pages.mjs from the old TanStack route files.
// Nesting mirrors TanStack's flat-file rules. Safe to hand-edit from here on.
import { createBrowserRouter } from "react-router-dom";
import { AppRoot, RootErrorBoundary, RootNotFound } from "./App";
import { GuestOnly, RequireAuth } from "@/lib/auth/auth-guards";
import HomePage from "@/pages/home/HomePage";
import DashboardPage from "@/pages/dashboard/DashboardPage";
import LocationsLayout from "@/pages/locations/LocationsLayout";
import LocationsIndexPage from "@/pages/locations/LocationsIndexPage";
import LocationsAddPage from "@/pages/locations/LocationsAddPage";
import LocationDetailIndexPage from "@/pages/locations/location-detail/LocationDetailIndexPage";
import LocationReportsPage from "@/pages/locations/location-detail/report/LocationReportsPage";
import GbpLayout from "@/pages/locations/location-detail/gbp/GbpLayout";
import LocationGbpIndexPage from "@/pages/locations/location-detail/gbp/GbpIndexPage";
import LocationGbpPostsPage from "@/pages/locations/location-detail/gbp/GbpPostsPage";
import LocationGbpReviewsPage from "@/pages/locations/location-detail/gbp/GbpReviewsPage";
import GbpAuditLayout from "@/pages/locations/location-detail/gbp/audit/GbpAuditLayout";
import GbpAuditIndexPage from "@/pages/locations/location-detail/gbp/audit/GbpAuditIndexPage";
import GbpAuditCompetitorsPage from "@/pages/locations/location-detail/gbp/audit/GbpAuditCompetitorsPage";
import RankingsLayout from "@/pages/locations/location-detail/rankings/RankingsLayout";
import LocationRankingsIndexPage from "@/pages/locations/location-detail/rankings/RankingsIndexPage";
import LocationRankingsKeywordsPage from "@/pages/locations/location-detail/rankings/RankingsKeywordsPage";
import RankingsGroupsPage from "@/pages/locations/location-detail/rankings/RankingsGroupsPage";
import RankingsGridPage from "@/pages/locations/location-detail/rankings/RankingsGridPage";
import RankingsMapPage from "@/pages/locations/location-detail/rankings/RankingsMapPage";
import RankingsCompetitorsPage from "@/pages/locations/location-detail/rankings/RankingsCompetitorsPage";
import CitationsIndexPage from "@/pages/locations/location-detail/citations/CitationsIndexPage";
import CitationDetailPage from "@/pages/locations/location-detail/citations/CitationDetailPage";
import CompetitorsIndexPage from "@/pages/locations/location-detail/competitors/CompetitorsIndexPage";
import CompetitorDetailPage from "@/pages/locations/location-detail/competitors/CompetitorDetailPage";
import RankingsIndexPage from "@/pages/rankings/RankingsIndexPage";
import RankingsKeywordsPage from "@/pages/rankings/RankingsKeywordsPage";
import RankingsKeywordGroupsPage from "@/pages/rankings/RankingsKeywordGroupsPage";
import RankingsMapRankingsPage from "@/pages/rankings/RankingsMapRankingsPage";
import RankingsLocalSearchGridPage from "@/pages/rankings/RankingsLocalSearchGridPage";
import GbpIndexPage from "@/pages/gbp/GbpIndexPage";
import GbpAuditPage from "@/pages/gbp/GbpAuditPage";
import GbpReviewsPage from "@/pages/gbp/GbpReviewsPage";
import GbpPostsPage from "@/pages/gbp/GbpPostsPage";
import GbpAiPostsPage from "@/pages/gbp/GbpAiPostsPage";
import GbpAiPostCreatePage from "@/pages/gbp/GbpAiPostCreatePage";
import GbpAiPostDetailPage from "@/pages/gbp/GbpAiPostDetailPage";
import GbpReviewManagementPage from "@/pages/gbp/GbpReviewManagementPage";
import GbpReviewAutomationPage from "@/pages/gbp/GbpReviewAutomationPage";
import GbpConnectCallbackPage from "@/pages/gbp/GbpConnectCallbackPage";
import CitationsPage from "@/pages/citations/CitationsPage";
import CompetitorsPage from "@/pages/competitors/CompetitorsPage";
import AiVisibilityPage from "@/pages/ai-visibility/AiVisibilityPage";
import ReportsIndexPage from "@/pages/reports/ReportsIndexPage";
import ReportsCreatePage from "@/pages/reports/ReportsCreatePage";
import ReportsScheduledPage from "@/pages/reports/ReportsScheduledPage";
import ReportDetailPage from "@/pages/reports/ReportDetailPage";
import ClientsIndexPage from "@/pages/clients/ClientsIndexPage";
import ClientLayout from "@/pages/clients/client-detail/ClientLayout";
import ClientIndexPage from "@/pages/clients/client-detail/ClientIndexPage";
import ClientLocationsPage from "@/pages/clients/client-detail/ClientLocationsPage";
import ClientUsersPage from "@/pages/clients/client-detail/ClientUsersPage";
import AutomationsIndexPage from "@/pages/automations/AutomationsIndexPage";
import AutomationsCreatePage from "@/pages/automations/AutomationsCreatePage";
import AutomationDetailPage from "@/pages/automations/AutomationDetailPage";
import SettingsLayout from "@/pages/settings/SettingsLayout";
import SettingsIndexPage from "@/pages/settings/SettingsIndexPage";
import SettingsProfilePage from "@/pages/settings/SettingsProfilePage";
import SettingsBillingPage from "@/pages/settings/SettingsBillingPage";
import SettingsTeamPage from "@/pages/settings/SettingsTeamPage";
import SettingsIntegrationsPage from "@/pages/settings/SettingsIntegrationsPage";
import SettingsNotificationsPage from "@/pages/settings/SettingsNotificationsPage";
import SettingsWhiteLabelPage from "@/pages/white-label/SettingsWhiteLabelPage";
import WhiteLabelPreviewPage from "@/pages/white-label/WhiteLabelPreviewPage";
import NotificationsPage from "@/pages/notifications/NotificationsPage";
import HelpPage from "@/pages/help/HelpPage";
import OnboardingIndexPage from "@/pages/onboarding/OnboardingIndexPage";
import OnboardingBusinessPage from "@/pages/onboarding/OnboardingBusinessPage";
import OnboardingAgencyPage from "@/pages/onboarding/OnboardingAgencyPage";
import LoginPage from "@/pages/auth/LoginPage";
import SignupPage from "@/pages/auth/SignupPage";
import ForgotPasswordPage from "@/pages/auth/ForgotPasswordPage";
import ResetPasswordPage from "@/pages/auth/ResetPasswordPage";
import VerifyEmailPage from "@/pages/auth/VerifyEmailPage";
import VerifyOtpPage from "@/pages/auth/VerifyOtpPage";
import ForbiddenPage from "@/pages/errors/ForbiddenPage";
import NotFoundPage from "@/pages/errors/NotFoundPage";

export const router = createBrowserRouter([
  {
    path: "/",
    Component: AppRoot,
    ErrorBoundary: RootErrorBoundary,
    children: [
      { index: true, Component: HomePage },
      {
        // Signed-in pages: no valid token sends the user to /login.
        Component: RequireAuth,
        children: [
          { path: "dashboard", Component: DashboardPage },
          {
            path: "locations",
            Component: LocationsLayout,
            children: [
              { index: true, Component: LocationsIndexPage },
              { path: "add", Component: LocationsAddPage },
              { path: ":locationId", Component: LocationDetailIndexPage },
              { path: ":locationId/reports", Component: LocationReportsPage },
              {
                path: ":locationId/gbp",
                Component: GbpLayout,
                children: [
                  { index: true, Component: LocationGbpIndexPage },
                  { path: "posts", Component: LocationGbpPostsPage },
                  { path: "reviews", Component: LocationGbpReviewsPage },
                  {
                    path: "audit",
                    Component: GbpAuditLayout,
                    children: [
                      { index: true, Component: GbpAuditIndexPage },
                      { path: "competitors", Component: GbpAuditCompetitorsPage },
                    ],
                  },
                ],
              },
              {
                path: ":locationId/rankings",
                Component: RankingsLayout,
                children: [
                  { index: true, Component: LocationRankingsIndexPage },
                  { path: "keywords", Component: LocationRankingsKeywordsPage },
                  { path: "groups", Component: RankingsGroupsPage },
                  { path: "grid", Component: RankingsGridPage },
                  { path: "map", Component: RankingsMapPage },
                  { path: "competitors", Component: RankingsCompetitorsPage },
                ],
              },
              { path: ":locationId/citations", Component: CitationsIndexPage },
              { path: ":locationId/citations/:citationId", Component: CitationDetailPage },
              { path: ":locationId/competitors", Component: CompetitorsIndexPage },
              { path: ":locationId/competitors/:competitorId", Component: CompetitorDetailPage },
            ],
          },
          { path: "rankings", Component: RankingsIndexPage },

          { path: "rankings/keywords", Component: RankingsKeywordsPage },
          { path: "rankings/keyword-groups", Component: RankingsKeywordGroupsPage },
          { path: "rankings/map-rankings", Component: RankingsMapRankingsPage },
          { path: "rankings/local-search-grid", Component: RankingsLocalSearchGridPage },
          { path: "gbp", Component: GbpIndexPage },
          { path: "gbp/audit", Component: GbpAuditPage },
          { path: "gbp/reviews", Component: GbpReviewsPage },
          { path: "gbp/posts", Component: GbpPostsPage },
          { path: "gbp/ai-posts", Component: GbpAiPostsPage },
          { path: "gbp/ai-posts/create", Component: GbpAiPostCreatePage },
          { path: "gbp/ai-posts/:postId", Component: GbpAiPostDetailPage },
          { path: "gbp/review-management", Component: GbpReviewManagementPage },
          { path: "gbp/review-management/automation", Component: GbpReviewAutomationPage },
          // Google OAuth redirect target for the Business Profile connection.
          { path: "gbp/connect/callback", Component: GbpConnectCallbackPage },
          { path: "citations", Component: CitationsPage },
          { path: "competitors", Component: CompetitorsPage },
          { path: "ai-visibility", Component: AiVisibilityPage },
          { path: "reports", Component: ReportsIndexPage },
          { path: "reports/create", Component: ReportsCreatePage },
          { path: "reports/scheduled", Component: ReportsScheduledPage },
          { path: "reports/:reportId", Component: ReportDetailPage },
          { path: "clients", Component: ClientsIndexPage },
          {
            path: "clients/:clientId",
            Component: ClientLayout,
            children: [
              { index: true, Component: ClientIndexPage },
              { path: "locations", Component: ClientLocationsPage },
              { path: "users", Component: ClientUsersPage },
            ],
          },
          { path: "automations", Component: AutomationsIndexPage },
          { path: "automations/create", Component: AutomationsCreatePage },
          { path: "automations/:automationId", Component: AutomationDetailPage },
          {
            path: "settings",
            Component: SettingsLayout,
            children: [
              { index: true, Component: SettingsIndexPage },
              { path: "profile", Component: SettingsProfilePage },
              { path: "billing", Component: SettingsBillingPage },
              { path: "team", Component: SettingsTeamPage },
              { path: "integrations", Component: SettingsIntegrationsPage },
              { path: "notifications", Component: SettingsNotificationsPage },
              { path: "white-label", Component: SettingsWhiteLabelPage },
              { path: "white-label/preview/:reportId?", Component: WhiteLabelPreviewPage },
            ],
          },
          { path: "notifications", Component: NotificationsPage },
          { path: "help", Component: HelpPage },
          { path: "onboarding", Component: OnboardingIndexPage },
          { path: "onboarding/business", Component: OnboardingBusinessPage },
          { path: "onboarding/agency", Component: OnboardingAgencyPage },
        ],
      },
      {
        // Sign In / Sign Up: an already signed-in user goes straight to the app.
        Component: GuestOnly,
        children: [
          { path: "login", Component: LoginPage },
          { path: "signup", Component: SignupPage },
        ],
      },
      { path: "forgot-password", Component: ForgotPasswordPage },
      { path: "reset-password", Component: ResetPasswordPage },
      { path: "verify-email", Component: VerifyEmailPage },
      { path: "verify-otp", Component: VerifyOtpPage },
      { path: "403", Component: ForbiddenPage },
      { path: "404", Component: NotFoundPage },
      { path: "*", Component: RootNotFound },
    ],
  },
]);

export default router;
