import type { ReactNode } from "react";
import { Asterisk, Bot, Compass, FlaskConical, Info, Sparkles, type LucideIcon } from "lucide-react";
import { TrendIndicator } from "@/components/layout/shared/data-display";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { AI_PLATFORM_COLOR, AI_PLATFORM_LABEL, formatSigned, type AiPlatform } from "@/lib/ai-visibility/ai-visibility";
import { cn } from "@/lib/utils";

/** Generic, non-branded glyphs so platforms read as a set without using logos. */
const PLATFORM_GLYPH: Record<AiPlatform, LucideIcon> = {
  chatgpt: Bot,
  gemini: Sparkles,
  perplexity: Compass,
  claude: Asterisk,
};

export function PlatformIcon({ platform, size = "md", className }: { platform: AiPlatform; size?: "sm" | "md"; className?: string }) {
  const Glyph = PLATFORM_GLYPH[platform];
  return (
    <span
      aria-hidden
      className={cn(
        "relative flex shrink-0 items-center justify-center rounded-md border border-border bg-surface-strong text-foreground/80",
        size === "sm" ? "size-6" : "size-9",
        className,
      )}
    >
      <Glyph className={size === "sm" ? "size-3.5" : "size-4"} />
      <span
        className={cn("absolute -bottom-0.5 -right-0.5 rounded-full ring-2 ring-surface", size === "sm" ? "size-2" : "size-2.5")}
        style={{ background: AI_PLATFORM_COLOR[platform] }}
      />
    </span>
  );
}

export function PlatformLabel({ platform }: { platform: AiPlatform }) {
  return (
    <span className="inline-flex items-center gap-2 whitespace-nowrap">
      <PlatformIcon platform={platform} size="sm" />
      {AI_PLATFORM_LABEL[platform]}
    </span>
  );
}

/** Small "i" button explaining how a metric is measured. */
export function InfoTooltip({ label, children }: { label: string; children: ReactNode }) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <button
          type="button"
          aria-label={`About ${label}`}
          className="inline-flex size-5 items-center justify-center rounded-full text-muted-foreground transition-colors hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40"
        >
          <Info className="size-3.5" aria-hidden />
        </button>
      </TooltipTrigger>
      <TooltipContent className="max-w-64 leading-relaxed">{children}</TooltipContent>
    </Tooltip>
  );
}

/** Labels content generated by the demo layer instead of a real AI provider. */
export function SampleDataBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-md border border-warning/35 bg-warning-surface px-2 py-0.5 text-[11px] font-medium text-warning-foreground",
        className,
      )}
    >
      <FlaskConical className="size-3" aria-hidden />
      Sample data
    </span>
  );
}

/** Trend arrow + signed value; renders nothing when there is no baseline. */
export function ChangeIndicator({ value, suffix = "%", className }: { value: number | null; suffix?: string; className?: string }) {
  if (value === null) return <span className={cn("text-xs text-muted-foreground", className)}>—</span>;
  const direction = value > 0 ? "up" : value < 0 ? "down" : "flat";
  return <TrendIndicator direction={direction} value={formatSigned(value, suffix)} {...(className ? { className } : {})} />;
}

/** Thin 0–100 meter used for visibility percentages. */
export function VisibilityMeter({ value, className }: { value: number; className?: string }) {
  return (
    <div className={cn("h-1.5 w-full overflow-hidden rounded-full bg-muted", className)}>
      <div className="h-full rounded-full bg-primary" style={{ width: `${Math.min(Math.max(value, 0), 100)}%` }} />
    </div>
  );
}
