/** Demo dataset for the notifications surfaces (header + inbox). */
import { demoDate } from "./demo-mode";
import type { NotificationItem } from "../notifications";

export function demoNotifications(): NotificationItem[] {
  return [
    {
      id: "ntf_1",
      category: "ranking",
      title: 'Ranking improved for "emergency dentist austin"',
      description: "Riverside Dental — North Austin moved from #6 to #3 in the Local Pack.",
      createdAt: demoDate(0),
      read: false,
      clientId: "cl_riverside",
      clientName: "Riverside Dental Group",
      locationId: "loc_riverside_north",
      locationName: "Riverside Dental — North Austin",
      target: { kind: "location_rankings", locationId: "loc_riverside_north" },
    },
    {
      id: "ntf_2",
      category: "review",
      title: "New 5-star review",
      description: "Hearth & Oak — Downtown received a new Google review.",
      createdAt: demoDate(0),
      read: false,
      clientId: "cl_hearth",
      clientName: "Hearth & Oak Restaurants",
      locationId: "loc_hearth_downtown",
      locationName: "Hearth & Oak — Downtown",
      target: { kind: "location_reviews", locationId: "loc_hearth_downtown" },
    },
    {
      id: "ntf_3",
      category: "gbp",
      title: "GBP audit found a new issue",
      description: "Hearth & Oak — Cherry Creek has no Google Post published in 30 days.",
      createdAt: demoDate(1),
      read: false,
      clientId: "cl_hearth",
      clientName: "Hearth & Oak Restaurants",
      locationId: "loc_hearth_cherry",
      locationName: "Hearth & Oak — Cherry Creek",
      target: { kind: "location_gbp", locationId: "loc_hearth_cherry" },
    },
    {
      id: "ntf_4",
      category: "citation",
      title: "Citation inconsistency detected",
      description: "Lumen Family Law has a NAP mismatch on Yelp.",
      createdAt: demoDate(2),
      read: true,
      clientId: "cl_lumen",
      clientName: "Lumen Family Law",
      locationId: "loc_lumen_main",
      locationName: "Lumen Family Law — Austin",
      target: { kind: "location_citations", locationId: "loc_lumen_main" },
    },
    {
      id: "ntf_5",
      category: "report",
      title: "Report generated",
      description: "Riverside Dental — North Austin Rank Tracker report is ready to view.",
      createdAt: demoDate(3),
      read: true,
      clientId: "cl_riverside",
      clientName: "Riverside Dental Group",
      locationId: "loc_riverside_north",
      locationName: "Riverside Dental — North Austin",
      target: { kind: "report", reportId: "rep_1" },
    },
    {
      id: "ntf_6",
      category: "automation",
      title: "Automation run failed",
      description:
        "Ranking drop alert for Hearth & Oak — Cherry Creek could not refresh 2 keywords.",
      createdAt: demoDate(2),
      read: false,
      clientId: "cl_hearth",
      clientName: "Hearth & Oak Restaurants",
      locationId: "loc_hearth_cherry",
      locationName: "Hearth & Oak — Cherry Creek",
      target: { kind: "automation", automationId: "auto_hearth_ranking" },
    },
    {
      id: "ntf_7",
      category: "gbp",
      title: "Google connection needs reauthorization",
      description: "Riverside Dental — South Lamar stopped syncing profile data.",
      createdAt: demoDate(4),
      read: true,
      clientId: "cl_riverside",
      clientName: "Riverside Dental Group",
      locationId: "loc_riverside_south",
      locationName: "Riverside Dental — South Lamar",
      target: { kind: "location_gbp", locationId: "loc_riverside_south" },
    },
    {
      id: "ntf_8",
      category: "billing",
      title: "Invoice paid",
      description: "Invoice MPS-2026-0009 was paid successfully.",
      createdAt: demoDate(9),
      read: true,
      target: { kind: "billing" },
    },
  ];
}
